---
- hosts: all
  name: Firmware Update
  connection: local
  gather_facts: False
  vars_files:
    - "{{ ANSIBLE_EXTERNAL_VARS }}"
    - "{{ ANSIBLE_PASSWORDS }}"

  tasks:
  - name: Validate technical_state_path variable
    assert:
      that:
        - technical_state_path is defined
      fail_msg: "The variable technical_state_path is NOT defined in inventory (AWX) or vars/external_vars file (Ansible). See readme.md for more details."
      success_msg: "The variable technical_state_path is defined"
    run_once: true

  - debug:
      msg: "technical_state_path is {{ technical_state_path }}"
    when: technical_state_path is defined
    run_once: true

  - include_tasks: ../utils/utils_create_token.yml

  - include_tasks: ../utils/utils_firmware_inventory.yml

  - include_tasks: ../utils/utils_evaluate_firmware_update.yml

  - include_tasks: ../utils/utils_upload_firmwares.yml

