---
- hosts: all
  connection: local
  name: Sensor Inventory
  gather_facts: False
  vars_files:
    - "{{ ANSIBLE_EXTERNAL_VARS }}"
    - "{{ ANSIBLE_PASSWORDS }}"

  tasks:
  - name: create auth token
    include_tasks: ../utils/utils_create_token.yml

  - name: get sensors
    uri:
      url: "https://{{ baseuri }}/xyz/openbmc_project/sensors/enumerate"
      method: GET
      validate_certs: no
      headers:
        X-Auth-Token: "{{ x_token }}"    
    register: result_sensors

  - set_fact:
      check_sensors: "{{ result_sensors.json.data }}"

  - name: check Critical Alarms
    debug: 
      var: check_sensors
    when: check_sensors is defined

  - name: check Critical Alarm Low
    debug:
      var: item.value
      verbosity: 2
    failed_when: "{{ item.value.CriticalAlarmLow }} == true and {{ item.value.Value }} != 0"
    with_dict: "{{ check_sensors }}"

  - name: check Critical Alarm High
    debug:
      var: item.value
      verbosity: 2
    failed_when: "{{ item.value.CriticalAlarmHigh }} == true and {{ item.value.Value }} != 0"
    with_dict: "{{ check_sensors }}"
